#Note, requires Vault to support all economies. Fallback economy is EssentialsEco, so if this is not your currency base it is suggested you install Vault

MaxServantTime: 7d
CanFreeHired: true
FreedHiredGetsPartPay: true
MinDailyWage: 0
ContinuousWage: true # Daily wage is not given all at once, but steadily over time

MaxServants: 0 #0 for no limit
AllowServantsToOwnServants: true

# Put a hash mark before an ability to make it always allowed
MasterCanRestrict:
   - breakblocks
   - placeblocks
   - emptybucket
#  - interacblock
   - interactentity
   - attack
   - attackmonster
   - attackanimal
   - attackplayer
   - attackmaster
   - ridemob
   - usechests
   - teleport
   - ownservants
#  - commands
   - enter_bed
   
# List of what items a master is allowed to collect from a servant
MasterCanCollect:
   - items
   - armor
   - xp
   - servants